### ISSUE TITLE
ros_ark_header -> uncompressed_length should be unsigend long

### ISSUE THREAD

**Issue by weidenba** [iam-TJ/ros_pack#1]
I had a look at some ros-packed firmwares recently. All of them used lzma compressed data.
The LZMA-Specs states that the uncompressed size is encoded as 64 bit uncompressed integer. 
So it sounds reasonable to me that uncompressed_length is unsigend long.

LZMA specification can be downloaded here: http://7-zip.org/sdk.html

**Comment by iam-TJ** [comment]
Yes, but everything I've seen so far suggests ROS PACK is designed and built for, at most, 32-bit processors. Combine that fact with the knowledge that the firmware writers make free with custom LZMA implementations, and I'm loath to declare the field an 'unsigned long' until I find evidence of its use. The other issue is determining whether this field is ever written in Big Endian format, since as an unsigned long, that would impact on which of the surrounding (unknown) bytes belong to the field.

**Comment by iam-TJ** [comment]
Confirmed that the value is 32-bit (I've seen several sub-headers where the unsigned int values on either side of uncompressed_length contain values that would make the uncompressed_length wildly incorrect.)
